/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author xor
 */
public class BuyerLoginFrame extends javax.swing.JFrame {
    
     /**
     * Creates new form BuyerLoginFrame
     */ 
    private String[] imgslides={"/img/bgimg1.png","/img/bgimg2.png","/img/bgimg3.png"};
    private int imageIndex = 0;
    
   private void imageSlideshow() {

    Timer timer = new Timer(8000, e -> {
        imageIndex = (imageIndex + 1) % imgslides.length;

        bgimg.setIcon(
            new ImageIcon(getClass().getResource(imgslides[imageIndex])));
    });
    timer.start();
}

    public BuyerLoginFrame() {
        initComponents();
        imageSlideshow();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Logo = new javax.swing.JLabel();
        GroupName1 = new javax.swing.JLabel();
        LoginForm = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        userName = new javax.swing.JTextField();
        Password = new javax.swing.JLabel();
        userPass = new javax.swing.JPasswordField();
        noaccount = new javax.swing.JLabel();
        shiftForms = new javax.swing.JButton();
        login = new javax.swing.JButton();
        switchAccount = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bgimg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1279, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setFont(new java.awt.Font("New Peninim MT", 1, 24)); // NOI18N
        Logo.setForeground(new java.awt.Color(255, 255, 255));
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/miniLogo.png"))); // NOI18N
        getContentPane().add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 90));

        GroupName1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        GroupName1.setForeground(new java.awt.Color(130, 159, 120));
        GroupName1.setText("C R E A M S");
        getContentPane().add(GroupName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 35, 524, 30));

        LoginForm.setBackground(new java.awt.Color(30, 30, 30));
        LoginForm.setFocusable(false);
        LoginForm.setMaximumSize(new java.awt.Dimension(1280, 92));
        LoginForm.setMinimumSize(new java.awt.Dimension(1280, 92));
        LoginForm.setPreferredSize(new java.awt.Dimension(1280, 92));
        LoginForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Arial", 1, 32)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("<html>Welcome, Buyer!</html>");
        Title.setToolTipText("");
        LoginForm.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 400, -1));

        Username.setFont(new java.awt.Font("New Peninim MT", 0, 15)); // NOI18N
        Username.setForeground(new java.awt.Color(255, 255, 255));
        Username.setText("Email");
        LoginForm.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 135, -1, -1));

        userName.setFont(new java.awt.Font("New Peninim MT", 0, 18)); // NOI18N
        userName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        userName.setText("test");
        userName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameActionPerformed(evt);
            }
        });
        LoginForm.add(userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 155, 320, 40));

        Password.setFont(new java.awt.Font("New Peninim MT", 0, 15)); // NOI18N
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setText("Password");
        LoginForm.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        userPass.setFont(new java.awt.Font("New Peninim MT", 0, 18)); // NOI18N
        userPass.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        userPass.setText("jPasswordField1");
        userPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userPassActionPerformed(evt);
            }
        });
        LoginForm.add(userPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 320, 40));

        noaccount.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        noaccount.setForeground(new java.awt.Color(255, 255, 255));
        noaccount.setText("Don't have an account?");
        LoginForm.add(noaccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        shiftForms.setFont(new java.awt.Font("New Peninim MT", 0, 10)); // NOI18N
        shiftForms.setText("Register");
        shiftForms.setAlignmentY(0.0F);
        shiftForms.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        shiftForms.setBorderPainted(false);
        shiftForms.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        shiftForms.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        shiftForms.setMargin(new java.awt.Insets(14, 14, 14, 14));
        shiftForms.setOpaque(true);
        shiftForms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shiftFormsActionPerformed(evt);
            }
        });
        LoginForm.add(shiftForms, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 397, 80, 20));

        login.setBackground(new java.awt.Color(0, 0, 0));
        login.setFont(new java.awt.Font("New Peninim MT", 1, 24)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("Login");
        login.setAlignmentY(0.0F);
        login.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        login.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        login.setFocusPainted(false);
        login.setFocusable(false);
        login.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        login.setIconTextGap(0);
        login.setMargin(new java.awt.Insets(14, 14, 14, 14));
        login.setSelected(true);
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        LoginForm.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 310, 300, 40));

        switchAccount.setBackground(new java.awt.Color(102, 102, 102));
        switchAccount.setFont(new java.awt.Font("New Peninim MT", 1, 10)); // NOI18N
        switchAccount.setForeground(new java.awt.Color(255, 255, 255));
        switchAccount.setText("Switch to Staff Portal");
        switchAccount.setAlignmentY(0.0F);
        switchAccount.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        switchAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        switchAccount.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        switchAccount.setMargin(new java.awt.Insets(14, 14, 14, 14));
        switchAccount.setOpaque(true);
        switchAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchAccountActionPerformed(evt);
            }
        });
        LoginForm.add(switchAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 340, 20));

        getContentPane().add(LoginForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(755, 162, 401, 474));

        jPanel1.setBackground(new java.awt.Color(30, 30, 30));
        jPanel1.setFocusable(false);
        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 92));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 92));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 92));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 92));

        jLabel1.setFont(new java.awt.Font("New Peninim MT", 1, 70)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("<html>B U Y E R <br> P O R T A L</html>");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 233, 524, 288));

        bgimg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bgimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/main_bg.png"))); // NOI18N
        getContentPane().add(bgimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameActionPerformed

    private void userPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userPassActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        String email = userName.getText();
        String password = new String(userPass.getPassword());
        
        models.User user = controller.UserManager.getInstance().login(email, password);

        if (user instanceof models.Buyer) {
            BuyerDashboard dashboard = new BuyerDashboard();
            dashboard.setVisible(true);
            this.dispose();
        } 
        else if(user instanceof models.Agent || user instanceof models.Admin) {
            javax.swing.JOptionPane.showMessageDialog(this, "Staff must use the Staff Portal.", "Access Denied", javax.swing.JOptionPane.WARNING_MESSAGE);
        }
        else {
            javax.swing.JOptionPane.showMessageDialog(this, "Invalid Buyer Credentials!", "Login Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_loginActionPerformed

    private void shiftFormsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shiftFormsActionPerformed
        // TODO add your handling code here:
        RegisterAccountFrame registerFrame=new RegisterAccountFrame();
        registerFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_shiftFormsActionPerformed

    private void switchAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchAccountActionPerformed
        // TODO add your handling code here:
        StaffLoginFrame AgentLoginFrame=new StaffLoginFrame();
        AgentLoginFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_switchAccountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuyerLoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuyerLoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuyerLoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuyerLoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuyerLoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GroupName1;
    private javax.swing.JPanel LoginForm;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel Username;
    private javax.swing.JLabel bgimg;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton login;
    private javax.swing.JLabel noaccount;
    private javax.swing.JButton shiftForms;
    private javax.swing.JButton switchAccount;
    private javax.swing.JTextField userName;
    private javax.swing.JPasswordField userPass;
    // End of variables declaration//GEN-END:variables
}
