/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Paul Joel D. Perez <pjdperez@mymail.mapua.edu.ph>
 */

package gui;

import javax.swing.*;
import java.awt.*;
import models.Lot;

public class LotFilterPanel extends JPanel {
    private JComboBox<String> statusFilter;
    private JComboBox<String> blockFilter;
    private JComboBox<String> lotFilter;
    private JComboBox<String> priceFilter;
    private JButton applyFilterBtn;

    public LotFilterPanel(Runnable applyAction) {
        setBackground(new Color(30, 30, 30));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        
        ImageIcon icon = new ImageIcon(getClass().getResource("/img/filters.png"));
        Image img = icon.getImage().getScaledInstance(24, 24, Image.SCALE_SMOOTH);
        icon = new ImageIcon(img);


        JLabel title = new JLabel("Filters:", icon, JLabel.LEFT);
        title.setFont(new Font("Arial", Font.BOLD, 24)); // Replaced non-standard font
        title.setForeground(Color.WHITE);
        add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 30, -1, -1));

        JLabel sFilter = new JLabel("Status:");
        sFilter.setFont(new Font("Arial", Font.BOLD, 18));
        sFilter.setForeground(Color.WHITE);
        add(sFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 65, -1, -1));

        statusFilter = new JComboBox<>(new String[]{"All", "Vacant", "Reserved", "Occupied"});
        add(statusFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 65, 120, -1));

        JLabel bFilter = new JLabel("Block:");
        bFilter.setFont(new Font("Arial", Font.BOLD, 18));
        bFilter.setForeground(Color.WHITE);
        add(bFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 65, -1, -1));

        blockFilter = new JComboBox<>(new String[]{"All", "Block 1", "Block 2", "Block 3", "Block 4", "Block 5"});
        add(blockFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 65, 120, -1));

        JLabel lFilter = new JLabel("Type:");
        lFilter.setFont(new Font("Arial", Font.BOLD, 18));
        lFilter.setForeground(Color.WHITE);
        add(lFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 65, -1, -1));

        lotFilter = new JComboBox<>(new String[]{"All", "Callista", "AlliyahInner", "AlliyahOuter"});
        add(lotFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 65, 120, -1));
        JLabel pFilter = new JLabel("Max Price:");
        pFilter.setFont(new Font("Arial", Font.BOLD, 18));
        pFilter.setForeground(Color.WHITE);
        add(pFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 65, -1, -1));

        priceFilter = new JComboBox<>(new String[]{"All", "Max 3500000", "Max 5500000"});
        add(priceFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 65, 140, -1));        applyFilterBtn = new JButton("Apply Filter");
        applyFilterBtn.addActionListener(e -> applyAction.run());
        add(applyFilterBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 100, -1, -1));   
    }

    public boolean evaluateLot(Lot lot) {
        String status = statusFilter.getSelectedItem().toString();
        String type = lotFilter.getSelectedItem().toString();
        String price = priceFilter.getSelectedItem().toString();
        String block = blockFilter.getSelectedItem().toString();

        String currentStatus = lot.getStatus();
        if (!status.equals("All")) {
            if (status.equals("Vacant") && !currentStatus.equalsIgnoreCase("Available")) return false;
            if (status.equals("Reserved") && !(currentStatus.equalsIgnoreCase("Reserved") || currentStatus.toLowerCase().contains("pending"))) return false;
            if (status.equals("Occupied") && !currentStatus.equalsIgnoreCase("Sold")) return false;
        }

        if (!type.equals("All") && !lot.getLotType().equalsIgnoreCase(type)) return false;

        double lotPrice = lot.getTcp();
        if (price.equals("Max 3500000") && lotPrice > 3500000) return false;
        if (price.equals("Max 5500000") && lotPrice > 5500000) return false;

        if (!block.equals("All") && !block.equals("Block " + lot.getBlockID())) return false;

        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
