/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author xor
 */
public class RegisterAccountFrame extends javax.swing.JFrame {
    
     /**
     * Creates new form BuyerLoginFrame
     */ 
    private String[] imgslides={"/img/bgimg1.png","/img/bgimg2.png","/img/bgimg3.png"};
    private int imageIndex = 0;
    
   private void imageSlideshow() {

    Timer timer = new Timer(8000, e -> {
        imageIndex = (imageIndex + 1) % imgslides.length;

        bgimg.setIcon(
            new ImageIcon(getClass().getResource(imgslides[imageIndex])));
    });
    timer.start();
}

    public RegisterAccountFrame() {
        initComponents();
        imageSlideshow();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GroupName1 = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        LoginForm = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        FirstName = new javax.swing.JLabel();
        firstName = new javax.swing.JTextField();
        LastName = new javax.swing.JLabel();
        lastName = new javax.swing.JTextField();
        Codename = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        Password = new javax.swing.JLabel();
        userPass = new javax.swing.JPasswordField();
        login = new javax.swing.JButton();
        noaccount = new javax.swing.JLabel();
        logAsStaff = new javax.swing.JButton();
        roleComboBox = new javax.swing.JComboBox<>();
        logAsBuyer = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bgimg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1279, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GroupName1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        GroupName1.setForeground(new java.awt.Color(130, 159, 120));
        GroupName1.setText("C R E A M S");
        getContentPane().add(GroupName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 35, 524, 30));

        Logo.setFont(new java.awt.Font("New Peninim MT", 1, 24)); // NOI18N
        Logo.setForeground(new java.awt.Color(255, 255, 255));
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/miniLogo.png"))); // NOI18N
        getContentPane().add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 90));

        LoginForm.setBackground(new java.awt.Color(30, 30, 30));
        LoginForm.setFocusable(false);
        LoginForm.setMaximumSize(new java.awt.Dimension(1280, 92));
        LoginForm.setMinimumSize(new java.awt.Dimension(1280, 92));
        LoginForm.setPreferredSize(new java.awt.Dimension(1280, 92));
        LoginForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Arial", 1, 32)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("<html>Register Account</html>");
        Title.setToolTipText("");
        LoginForm.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 400, -1));

        FirstName.setFont(new java.awt.Font("New Peninim MT", 0, 15)); // NOI18N
        FirstName.setForeground(new java.awt.Color(255, 255, 255));
        FirstName.setText("First Name");
        LoginForm.add(FirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        firstName.setFont(new java.awt.Font("New Peninim MT", 0, 18)); // NOI18N
        firstName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        firstName.setText("test");
        firstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameActionPerformed(evt);
            }
        });
        LoginForm.add(firstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 320, 40));

        LastName.setFont(new java.awt.Font("New Peninim MT", 0, 15)); // NOI18N
        LastName.setForeground(new java.awt.Color(255, 255, 255));
        LastName.setText("Last Name");
        LoginForm.add(LastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        lastName.setFont(new java.awt.Font("New Peninim MT", 0, 18)); // NOI18N
        lastName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        lastName.setText("test");
        lastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameActionPerformed(evt);
            }
        });
        LoginForm.add(lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 320, 40));

        Codename.setFont(new java.awt.Font("New Peninim MT", 0, 15)); // NOI18N
        Codename.setForeground(new java.awt.Color(255, 255, 255));
        Codename.setText("Email");
        LoginForm.add(Codename, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        emailField.setFont(new java.awt.Font("New Peninim MT", 0, 18)); // NOI18N
        emailField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        emailField.setText("email@test.com");
        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });
        LoginForm.add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 320, 40));

        Password.setFont(new java.awt.Font("New Peninim MT", 0, 15)); // NOI18N
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setText("Password");
        LoginForm.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        userPass.setFont(new java.awt.Font("New Peninim MT", 0, 18)); // NOI18N
        userPass.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        userPass.setText("jPasswordField1");
        userPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userPassActionPerformed(evt);
            }
        });
        LoginForm.add(userPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 320, 40));

        login.setBackground(new java.awt.Color(0, 0, 0));
        login.setFont(new java.awt.Font("New Peninim MT", 1, 24)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("Sign Up");
        login.setAlignmentY(0.0F);
        login.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        login.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        login.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        login.setMargin(new java.awt.Insets(14, 14, 14, 14));
        login.setOpaque(true);
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        LoginForm.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 385, 320, 40));

        noaccount.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        noaccount.setForeground(new java.awt.Color(255, 255, 255));
        noaccount.setText("Already have an account?");
        LoginForm.add(noaccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 445, -1, -1));

        logAsStaff.setFont(new java.awt.Font("New Peninim MT", 0, 10)); // NOI18N
        logAsStaff.setText("Login as Staff");
        logAsStaff.setAlignmentY(0.0F);
        logAsStaff.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        logAsStaff.setBorderPainted(false);
        logAsStaff.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        logAsStaff.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logAsStaff.setMargin(new java.awt.Insets(14, 14, 14, 14));
        logAsStaff.setOpaque(true);
        logAsStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logAsStaffActionPerformed(evt);
            }
        });
        LoginForm.add(logAsStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 80, 20));

        roleComboBox.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        roleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Buyer", "Agent", "Admin" }));
        roleComboBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        roleComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleComboBoxActionPerformed(evt);
            }
        });
        LoginForm.add(roleComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 65, 120, 30));

        logAsBuyer.setFont(new java.awt.Font("New Peninim MT", 0, 10)); // NOI18N
        logAsBuyer.setText("Login as Buyer");
        logAsBuyer.setAlignmentY(0.0F);
        logAsBuyer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        logAsBuyer.setBorderPainted(false);
        logAsBuyer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        logAsBuyer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logAsBuyer.setMargin(new java.awt.Insets(14, 14, 14, 14));
        logAsBuyer.setOpaque(true);
        logAsBuyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logAsBuyerActionPerformed(evt);
            }
        });
        LoginForm.add(logAsBuyer, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 80, 20));

        getContentPane().add(LoginForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(755, 162, 401, 474));

        jPanel1.setBackground(new java.awt.Color(30, 30, 30));
        jPanel1.setFocusable(false);
        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 92));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 92));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 92));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 92));

        jLabel2.setFont(new java.awt.Font("New Peninim MT", 1, 85)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CALLISTA");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 640, 70));

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("New Peninim MT", 0, 40)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("R E A L  E S T A T E");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 640, 70));

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("New Peninim MT", 0, 40)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("A N D  A C Q U I S I T I O N");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 640, 70));

        jLabel6.setFont(new java.awt.Font("New Peninim MT", 0, 40)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("M A N A G E M E N T");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 640, 70));

        jLabel3.setFont(new java.awt.Font("New Peninim MT", 0, 40)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("S Y S T E M");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 640, 70));

        bgimg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bgimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/main_bg.png"))); // NOI18N
        getContentPane().add(bgimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        String fName = firstName.getText().trim();
        String lName = lastName.getText().trim();
        String email = emailField.getText().trim();
        String password = new String(userPass.getPassword()).trim();
        String role = roleComboBox.getSelectedItem().toString();
        
        // Input Sanitation
        if (fName.isEmpty() || lName.isEmpty() || email.isEmpty() || password.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "All fields are required.", "Input Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (fName.contains(",") || lName.contains(",") || email.contains(",") || password.contains(",")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Commas are not allowed in input fields.", "Input Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (role.equals("Buyer")) {
            boolean success = controller.UserManager.getInstance().register(new models.Buyer(0, fName, lName, email, password));
            if (success) {
                javax.swing.JOptionPane.showMessageDialog(this, "Buyer Account Created Successfully.");
                new BuyerLoginFrame().setVisible(true);
                this.dispose();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Email already exists.", "Registration Failed", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } else if (role.equals("Admin")) {
            boolean success = controller.UserManager.getInstance().register(new models.Admin(0, fName, lName, email, password));
            if (success) {
                javax.swing.JOptionPane.showMessageDialog(this, "Admin Account Created Successfully.");
                new StaffLoginFrame().setVisible(true);
                this.dispose();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Email already exists.", "Registration Failed", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } else if (role.equals("Agent")) {
            AgentAssignment assignmentFrame = new AgentAssignment(this, true, fName, lName, email, password);
            assignmentFrame.setLocationRelativeTo(this);
            assignmentFrame.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_loginActionPerformed

    private void lastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameActionPerformed

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void logAsStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logAsStaffActionPerformed
        // TODO add your handling code here:
        StaffLoginFrame loginFrame = new StaffLoginFrame();
        loginFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_logAsStaffActionPerformed

    private void userPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userPassActionPerformed

    private void roleComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleComboBoxActionPerformed

    private void logAsBuyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logAsBuyerActionPerformed
        // TODO add your handling code here:
        BuyerLoginFrame BuyerLoginFrame=new BuyerLoginFrame();
        BuyerLoginFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_logAsBuyerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterAccountFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterAccountFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterAccountFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterAccountFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterAccountFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Codename;
    private javax.swing.JLabel FirstName;
    private javax.swing.JLabel GroupName1;
    private javax.swing.JLabel LastName;
    private javax.swing.JPanel LoginForm;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel bgimg;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField firstName;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lastName;
    private javax.swing.JButton logAsBuyer;
    private javax.swing.JButton logAsStaff;
    private javax.swing.JButton login;
    private javax.swing.JLabel noaccount;
    private javax.swing.JComboBox<String> roleComboBox;
    private javax.swing.JPasswordField userPass;
    // End of variables declaration//GEN-END:variables
}
